services:
  - type: web
    name: text-blind-watermark-web
    env: python
    buildCommand: "pip install -r app/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    plan: free
    autoDeploy: true
